# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: bcf-sdk
      url-base: https://github.com/jadonk

  #
  # Please add items below based on alphabetical order
  projects:
    - name: cmsis
      revision: b0612c97c1401feeb4160add6462c3627fe90fc7
      path: modules/hal/cmsis
      groups:
        - hal
    - name: hal_ti
      revision: pull/28/head
      path: modules/hal/ti
      groups:
        - hal
    - name: mbedtls
      revision: 711fd5ea13a5e018cebe1ac1f79c22d897e8b34d
      path: modules/crypto/mbedtls
      groups:
        - crypto
    - name: mcuboot
      revision: 225b02468bf77806bdd5f503725256cb345970d2
      path: bootloader/mcuboot
    - name: net-tools
      revision: f49bd1354616fae4093bf36e5eaee43c51a55127
      path: tools/net-tools
      groups:
        - tools
    - name: wpanusb_bc
      remote: bcf-sdk
      path: modules/lib/wpanusb_bc
      revision: main
    - name: greybus-for-zephyr
      remote: bcf-sdk
      path: modules/lib/greybus
      revision: mikrobus

  group-filter:
    - -ci

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
    import: submanifests
