# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: bcf-sdk
      url-base: https://github.com/jadonk
    - name: gb-fork
      url-base: https://git.beagleboard.org/gsoc

  #
  # Please add items below based on alphabetical order
  projects:
    - name: cmsis
      revision: 5f86244bad4ad5a590e084f0e72ba7a1416c2edf
      path: modules/hal/cmsis
      groups:
        - hal
    - name: hal_ti
      revision: c54f72e1a6be33733c684dcbbb47c84e8e332d68
      path: modules/hal/ti
      groups:
        - hal
    - name: mbedtls
      revision: 7fed49c9b9f983ad6416986661ef637459723bcb
      path: modules/crypto/mbedtls
      groups:
        - crypto
    - name: mcuboot
      revision: e7415b555134e671ba04f036b02f55cbc087d0e9
      path: bootloader/mcuboot
    - name: net-tools
      revision: f49bd1354616fae4093bf36e5eaee43c51a55127
      path: tools/net-tools
      groups:
        - tools
    - name: wpanusb_bc
      remote: bcf-sdk
      path: modules/lib/wpanusb_bc
      revision: main
    - name: greybus-for-zephyr
      remote: gb-fork
      path: modules/lib/greybus
      revision: 9fd1f60da38f0f3476428232cf90043b96abd64e
    - name: manifesto
      remote: bcf-sdk
      path: modules/lib/greybus/scripts/manifesto
      revision: main

  group-filter:
    - -ci

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
    import: submanifests
